[package]
name = "zkp"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
sha2 = "0.10"
bincode = { version = "2.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
